'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import React, { useState, useEffect, useRef } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { useLanguageStore } from '@/lib/store/language-store';
import { useWorkflowStore, GovernanceWorkflow, WorkflowLog } from '@/lib/store/workflow-store';
import { 
  Search, 
  MapPin, 
  Calendar, 
  Clock, 
  User, 
  Sparkles, 
  Send, 
  Upload, 
  CheckCircle, 
  ShieldAlert, 
  CheckCircle2,
  FileCheck2,
  Paperclip,
  TrendingUp,
  MessageSquare,
  Download,
  Maximize2
} from 'lucide-react';

const BACKEND_URL = "http://127.0.0.1:8000";

interface ClientChatMessage {
  id: number;
  sender_id: string;
  receiver_id: string;
  role: 'citizen' | 'officer';
  message: string;
  attachment_url?: string;
  created_at: string;
}

interface ResolutionReportData {
  conversational_text: string;
  problem_summary: string;
  ai_analysis: string;
  department_routing: string;
  actions_taken: string;
  urgency_reason: string;
  confidence_score: number;
  escalation_probability: string;
  estimated_completion: string;
  recommendations: string;
}

export default function TrackComplaint() {
  const { language, t } = useLanguageStore();
  const { workflows, activeWorkflowId, selectWorkflow, logs, isRunning, startSimulation, stopSimulation } = useWorkflowStore();

  const [searchQuery, setSearchQuery] = useState('');
  const [chatMessages, setChatMessages] = useState<ClientChatMessage[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isOfficerTyping, setIsOfficerTyping] = useState(false);
  const [attachedFile, setAttachedFile] = useState<string | null>(null);

  // Tab & Resolution Report states
  const [activeTab, setActiveTab] = useState<'telemetry' | 'diagram' | 'report'>('telemetry');
  const [reportLanguage, setReportLanguage] = useState<'en' | 'hi' | 'aw' | 'hl'>('en');
  const [resolutionReport, setResolutionReport] = useState<ResolutionReportData | null>(null);
  const [isLoadingReport, setIsLoadingReport] = useState(false);

  const activeWorkflow = workflows.find(w => w.id === activeWorkflowId) || workflows[0];
  const chatEndRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Sync language with standard app store on mount
  useEffect(() => {
    if (language) {
      setReportLanguage((language as 'en' | 'hi' | 'aw' | 'hl') || 'en');
    }
  }, [language]);

  async function fetchResolutionReport() {
    if (!activeWorkflow) return;
    setIsLoadingReport(true);
    try {
      const res = await fetch(`${BACKEND_URL}/api/v1/workflows/${activeWorkflow.id}/resolution-report?lang=${reportLanguage}`);
      if (res.ok) {
        const data = await res.json();
        setResolutionReport(data);
      }
    } catch (e) {
      console.log("Failed to load resolution report.");
    } finally {
      setIsLoadingReport(false);
    }
  }

  useEffect(() => {
    if (activeWorkflow) {
      fetchResolutionReport();
    }
  }, [activeWorkflowId, reportLanguage, activeWorkflow?.id]);

  const handleDownloadReport = () => {
    if (!resolutionReport || !activeWorkflow) return;
    const text = `
=========================================
      SARKARAI OS RESOLUTION REPORT
=========================================
Tracking ID: ${activeWorkflow.id}
Title: ${activeWorkflow.title}
Status: ${activeWorkflow.status.toUpperCase()}
Location: ${activeWorkflow.location}
-----------------------------------------
1. PROBLEM SUMMARY:
${resolutionReport.problem_summary}

2. AI DIAGNOSTIC ASSESSMENT:
${resolutionReport.ai_analysis}
Urgency Reason: ${resolutionReport.urgency_reason}
System Confidence Score: ${resolutionReport.confidence_score}%
Escalation Probability: ${resolutionReport.escalation_probability}

3. DEPARTMENT ROUTING:
${resolutionReport.department_routing}

4. CHRONOLOGICAL ACTIONS SEALED:
${resolutionReport.actions_taken}

5. PREDICTED COMPLETION DATE:
${resolutionReport.estimated_completion}

6. CONVERSATIONAL RECOMMENDATIONS:
${resolutionReport.recommendations}
-----------------------------------------
Generated by SarkarAI OS (सरकार एआई)
Date: ${new Date().toLocaleString()}
=========================================
`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `SarkarAI_Resolution_Report_${activeWorkflow.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // Animated Visual Workflow diagram nodes mapping
  const renderVisualWorkflowDiagram = () => {
    if (!activeWorkflow) return null;
    const progress = activeWorkflow.progress;
    
    const nodes = [
      { id: 1, name: "Citizen Ingestion", step: "input", minProgress: 10, label: "Citizen Complaint" },
      { id: 2, name: "AI Classification", step: "planner", minProgress: 15, label: "AI Routing" },
      { id: 3, name: "Verification Agent", step: "ocr", minProgress: 30, label: "OCR Identity Verification" },
      { id: 4, name: "Rule Engine Agent", step: "rules", minProgress: 50, label: "Bylaws & SLA Matching" },
      { id: 5, name: "Officer Desk", step: "officer", minProgress: 75, label: "Assigned Executive Reviewer" },
      { id: 6, name: "Audit Vault Check", step: "audit", minProgress: 90, label: "DM Signoff Audit" },
      { id: 7, name: "Final Resolution", step: "completed", minProgress: 100, label: "Ledger Sealing Vault" },
    ];

    return (
      <div className="flex flex-col gap-5 h-full overflow-y-auto pr-1 select-none">
        <div className="glass-card p-5 rounded-xl border border-white/5 relative overflow-hidden flex flex-col gap-4">
          <div className="absolute inset-0 cyber-grid opacity-5" />
          
          <div className="flex justify-between items-center z-10">
            <div className="flex flex-col">
              <span className="text-[9px] font-mono text-cyber-purple uppercase font-bold tracking-wider">Orchestration Graph Map</span>
              <h3 className="text-sm font-extrabold text-white mt-0.5">Live Agent Pipeline Canvas</h3>
            </div>
            
            <div className="flex items-center gap-2 text-[10px] font-mono text-cyber-purple bg-cyber-purple/10 border border-cyber-purple/20 px-2 py-0.5 rounded">
              <span className="h-1.5 w-1.5 rounded-full bg-cyber-purple animate-ping" />
              <span>Orchestrator active state: {activeWorkflow.currentStep.toUpperCase()}</span>
            </div>
          </div>

          <div className="w-full bg-[#02030b]/60 border border-white/5 p-4 rounded-xl relative z-10 flex flex-col justify-center min-h-[300px]">
            <div className="absolute inset-0 flex items-center justify-center opacity-10 pointer-events-none">
              <svg className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
                <pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse">
                  <path d="M 20 0 L 0 0 0 20" fill="none" stroke="rgba(188,19,254,0.4)" strokeWidth="0.5"/>
                </pattern>
                <rect width="100%" height="100%" fill="url(#grid)" />
              </svg>
            </div>

            <div className="flex flex-col gap-4 relative z-10 py-4 max-w-lg mx-auto w-full">
              {nodes.map((node, i) => {
                const isCompleted = progress > node.minProgress || (progress === 100 && node.minProgress === 100);
                const isActive = progress >= node.minProgress && progress < (nodes[i+1]?.minProgress || 101);
                
                return (
                  <div key={node.id} className="relative flex items-center gap-4 group">
                    {i < nodes.length - 1 && (
                      <div className="absolute left-[15px] top-8 bottom-[-20px] w-0.5 pointer-events-none z-0">
                        <div className={`
                          h-full w-full transition-all duration-500
                          \${isCompleted 
                            ? 'bg-gradient-to-b from-cyber-purple to-cyber-cyan shadow-[0_0_8px_rgba(188,19,254,0.5)]' 
                            : isActive
                              ? 'bg-gradient-to-b from-cyber-purple/50 to-white/5 border-dashed border-l border-cyber-purple/40 animate-pulse'
                              : 'bg-white/5 border-dashed border-l border-white/10'
                          }
                        `} />
                      </div>
                    )}

                    <div className={`
                      h-8 w-8 rounded-full flex items-center justify-center shrink-0 text-xs font-mono font-bold border-2 transition-all duration-500 z-10 shadow-md
                      \${isCompleted
                        ? 'bg-cyber-purple border-cyber-purple text-white shadow-[0_0_12px_rgba(188,19,254,0.6)]'
                        : isActive
                          ? 'bg-navy-950 border-cyber-cyan text-cyber-cyan shadow-[0_0_12px_#00f0ff] animate-pulse'
                          : 'bg-navy-950 border-white/10 text-white/30'
                      }
                    `}>
                      {node.id}
                    </div>

                    <div className={`
                      flex-1 p-2.5 rounded-lg border flex flex-col gap-0.5 leading-none transition-all duration-300
                      \${isCompleted
                        ? 'bg-white/[0.02] border-cyber-purple/20'
                        : isActive
                          ? 'bg-cyber-cyan/5 border-cyber-cyan/35 shadow-[0_0_10px_rgba(0,240,255,0.03)]'
                          : 'bg-white/5 border-white/5 opacity-40'
                      }
                    `}>
                      <div className="flex justify-between items-center">
                        <span className={`text-[10px] font-extrabold uppercase font-mono tracking-wider \${isActive ? 'text-cyber-cyan' : isCompleted ? 'text-cyber-purple' : 'text-white/40'}`}>
                          {node.name}
                        </span>
                        <span className="text-[8px] font-mono text-white/30">
                          {isCompleted ? 'VERIFIED' : isActive ? 'EXECUTING LIVE' : 'QUEUED'}
                        </span>
                      </div>
                      <span className="text-xs font-bold text-white/80 mt-1">{node.label}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        <div className="glass-card p-5 rounded-xl border border-white/5 flex flex-col gap-4 relative overflow-hidden">
          <div className="absolute inset-0 cyber-grid opacity-5 pointer-events-none" />
          
          <div className="flex items-center gap-2 border-b border-white/5 pb-2 shrink-0 z-10 relative">
            <Sparkles size={14} className="text-cyber-purple animate-pulse" />
            <h4 className="text-xs uppercase font-extrabold text-white font-mono tracking-wider">Explainable AI Core: &ldquo;How AI Solved This Case&rdquo;</h4>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs leading-relaxed text-white/70 relative z-10">
            <div className="flex flex-col gap-2 p-3 rounded bg-[#02030b]/60 border border-white/5">
              <span className="text-[10px] font-extrabold text-cyber-purple uppercase font-mono tracking-wider">AI Classification Rules Triggered:</span>
              <p>The system routed this query using semantic embeddings cosine similarity indexes. Standard keywords triggers classified the grievance type as <strong>{activeWorkflow.type.toUpperCase()}</strong> with a predicted confidence score of <strong>98.7%</strong>.</p>
            </div>
            
            <div className="flex flex-col gap-2 p-3 rounded bg-[#02030b]/60 border border-white/5">
              <span className="text-[10px] font-extrabold text-cyber-cyan uppercase font-mono tracking-wider">State SLA Decisions:</span>
              <p>Under Uttar Pradesh Smart Governance bylaws and PWD road guidelines, this priority was set to <strong>{activeWorkflow.type === 'grievance' ? 'HIGH / 72 hours SLA limit' : 'MEDIUM'}</strong>. The verification agent completed identity verification automatically via local registry checks.</p>
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderAiResolutionReport = () => {
    if (!activeWorkflow) return null;

    return (
      <div className="flex flex-col gap-5 h-full overflow-y-auto pr-1 select-none">
        
        <div className="flex justify-between items-center bg-white/5 p-2 rounded-xl border border-white/5 text-[10px] font-extrabold font-mono shrink-0">
          <span className="text-white/40 uppercase pl-2 flex items-center gap-1.5"><Sparkles size={11} className="text-cyber-pink animate-pulse" /> Language:</span>
          <div className="flex gap-1.5">
            {(['en', 'hi', 'aw', 'hl'] as const).map((l) => (
              <button
                key={l}
                onClick={() => setReportLanguage(l)}
                className={`px-3 py-1 rounded transition cursor-pointer \${
                  reportLanguage === l 
                    ? 'bg-cyber-pink text-white shadow-[0_0_10px_rgba(255,42,133,0.3)]' 
                    : 'text-white/50 hover:text-white hover:bg-white/5'
                }`}
              >
                {l === 'en' ? 'ENGLISH' : l === 'hi' ? 'हिन्दी (HINDI)' : l === 'aw' ? 'अवधी (AWADHI)' : 'HINGLISH'}
              </button>
            ))}
          </div>
        </div>

        {isLoadingReport || !resolutionReport ? (
          <div className="flex-1 glass-card p-12 flex flex-col justify-center items-center text-xs font-mono text-white/35">
            <div className="h-6 w-6 rounded-full border-2 border-cyber-pink border-t-transparent animate-spin mb-3" />
            <span>Analyzing workflow outcomes... Synthesizing dialect report...</span>
          </div>
        ) : (
          <div className="flex flex-col gap-5">
            
            <div className="glass-card p-5 rounded-xl border border-cyber-pink/20 relative overflow-hidden bg-gradient-to-r from-cyber-pink/5 via-cyber-purple/5 to-transparent">
              <div className="absolute inset-0 cyber-grid opacity-5 pointer-events-none" />
              <span className="text-[8px] font-mono text-cyber-pink uppercase font-extrabold tracking-wider">Citizen Advisory Message</span>
              <p className="text-[13px] font-sans font-medium text-white/95 mt-1.5 leading-relaxed italic pr-2">
                &ldquo;{resolutionReport.conversational_text}&rdquo;
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              
              <div className="glass-card p-4 rounded-xl border border-white/5 flex flex-col gap-3 font-sans">
                <span className="text-[9px] uppercase font-mono font-bold text-white/40 tracking-wider">1. Problem Summary</span>
                <p className="text-xs text-white/80 leading-relaxed font-medium bg-[#02030b]/60 p-2.5 rounded border border-white/5">
                  {resolutionReport.problem_summary}
                </p>
                
                <span className="text-[9px] uppercase font-mono font-bold text-white/40 tracking-wider mt-1">2. AI Diagnostic Assessment</span>
                <p className="text-xs text-white/80 leading-relaxed font-medium bg-[#02030b]/60 p-2.5 rounded border border-white/5">
                  {resolutionReport.ai_analysis}
                </p>
              </div>

              <div className="glass-card p-4 rounded-xl border border-white/5 flex flex-col gap-3 font-mono">
                <span className="text-[9px] uppercase font-bold text-white/40 tracking-wider">Sovereign Estimations Dashboard</span>
                
                <div className="grid grid-cols-2 gap-3 text-center">
                  <div className="flex flex-col p-2.5 rounded bg-navy-950 border border-white/5">
                    <span className="text-[8px] uppercase text-white/30 tracking-wider">Confidence Index</span>
                    <span className="text-base font-extrabold text-cyber-green mt-1">
                      {resolutionReport.confidence_score}%
                    </span>
                    <div className="w-full h-1 bg-white/5 rounded-full overflow-hidden mt-2">
                      <div className="h-full bg-cyber-green" style={{ width: `\${resolutionReport.confidence_score}%` }} />
                    </div>
                  </div>
                  
                  <div className="flex flex-col p-2.5 rounded bg-navy-950 border border-white/5">
                    <span className="text-[8px] uppercase text-white/30 tracking-wider">Escalation Probability</span>
                    <span className="text-base font-extrabold text-cyber-pink mt-1">
                      {resolutionReport.escalation_probability}
                    </span>
                    <div className="w-full h-1 bg-white/5 rounded-full overflow-hidden mt-2">
                      <div className="h-full bg-cyber-pink" style={{ width: `\${resolutionReport.escalation_probability}` }} />
                    </div>
                  </div>
                </div>

                <div className="flex flex-col gap-1 border-t border-white/5 pt-3 text-xs font-sans text-white/60 leading-relaxed">
                  <span className="text-[9px] font-mono uppercase font-bold text-white/40 tracking-wider">Decision Logic:</span>
                  <p>{resolutionReport.urgency_reason}</p>
                </div>
              </div>
            </div>

            <div className="glass-card p-4 rounded-xl border border-white/5 flex flex-col gap-4 font-sans text-xs">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="flex flex-col gap-1">
                  <span className="text-[9px] uppercase font-mono font-bold text-white/40 tracking-wider">3. Department & SLA desk Assignment</span>
                  <p className="text-white/80 leading-relaxed font-medium bg-[#02030b]/60 p-2.5 rounded border border-white/5">
                    {resolutionReport.department_routing}
                  </p>
                </div>
                
                <div className="flex flex-col gap-1">
                  <span className="text-[9px] uppercase font-mono font-bold text-white/40 tracking-wider">4. Chronological Actions Sealed</span>
                  <p className="text-white/80 leading-relaxed font-medium bg-[#02030b]/60 p-2.5 rounded border border-white/5">
                    {resolutionReport.actions_taken}
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-t border-white/5 pt-3">
                <div className="flex flex-col gap-1">
                  <span className="text-[9px] uppercase font-mono font-bold text-white/40 tracking-wider">5. Predicted Resolution date</span>
                  <p className="text-white/80 leading-relaxed font-medium bg-[#02030b]/60 p-2.5 rounded border border-white/5 flex items-center gap-1.5">
                    <Clock size={12} className="text-cyber-pink shrink-0 animate-pulse" /> {resolutionReport.estimated_completion}
                  </p>
                </div>

                <div className="flex flex-col gap-1">
                  <span className="text-[9px] uppercase font-mono font-bold text-white/40 tracking-wider">6. Recommendations & next steps</span>
                  <p className="text-white/80 leading-relaxed font-medium bg-[#02030b]/60 p-2.5 rounded border border-white/5">
                    {resolutionReport.recommendations}
                  </p>
                </div>
              </div>
            </div>

            <div className="glass-card p-4 rounded-xl border border-white/5 flex flex-col gap-3 font-mono">
              <span className="text-[9px] uppercase font-bold text-white/40 tracking-wider">Citizen Action follows-up</span>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center text-[10px] font-bold">
                <button 
                  onClick={() => setReportLanguage('hi')}
                  className="p-2.5 rounded bg-white/5 border border-white/5 hover:border-cyber-pink/30 hover:bg-cyber-pink/5 text-white transition cursor-pointer truncate"
                >
                  📄 READ HINDI (हिन्दी)
                </button>
                <button 
                  onClick={() => setReportLanguage('aw')}
                  className="p-2.5 rounded bg-white/5 border border-white/5 hover:border-cyber-pink/30 hover:bg-cyber-pink/5 text-white transition cursor-pointer truncate"
                >
                  🌾 READ AWADHI (अवधी)
                </button>
                <button 
                  onClick={() => {
                    setActiveTab('telemetry');
                    setTimeout(() => {
                      const chatInputEl = document.querySelector('input[placeholder*="Ask officer"]') as HTMLInputElement;
                      chatInputEl?.focus();
                    }, 200);
                  }}
                  className="p-2.5 rounded bg-white/5 border border-white/5 hover:border-cyber-cyan/30 hover:bg-cyber-cyan/5 text-cyber-cyan transition cursor-pointer truncate"
                >
                  💬 CONTACT OFFICER
                </button>
                <button 
                  onClick={() => {
                    setActiveTab('telemetry');
                    setTimeout(() => {
                      handlePresetAttachment(`${activeWorkflow.type}_evidence_record.pdf`);
                    }, 200);
                  }}
                  className="p-2.5 rounded bg-white/5 border border-white/5 hover:border-cyber-purple/30 hover:bg-cyber-purple/5 text-cyber-purple transition cursor-pointer truncate"
                >
                  📎 UPLOAD PROOF
                </button>
              </div>
            </div>

            <div className="flex gap-3 justify-end shrink-0 pt-2 font-mono text-xs">
              <button
                onClick={handleDownloadReport}
                className="px-4 py-2.5 rounded-lg bg-cyber-pink hover:opacity-90 hover:shadow-[0_0_15px_rgba(255,42,133,0.3)] text-white font-extrabold flex items-center justify-center gap-1.5 cursor-pointer transition uppercase"
              >
                <Download size={13} />
                <span>Export Report (.txt)</span>
              </button>
              
              <button
                onClick={() => window.print()}
                className="px-4 py-2.5 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-white font-bold flex items-center justify-center gap-1.5 cursor-pointer transition uppercase"
              >
                <Maximize2 size={13} />
                <span>Print PDF Report</span>
              </button>
            </div>

          </div>
        )}

      </div>
    );
  };

  async function fetchChatHistory() {
    if (!activeWorkflow) return;
    try {
      const res = await fetch(`${BACKEND_URL}/api/v1/workflows/${activeWorkflow.id}/chat`);
      if (res.ok) {
        const data = await res.json();
        setChatMessages(data);
      }
    } catch (e) {
      // Fallback local chat mock history - wrapped in setTimeout to defer rendering state change
      setTimeout(() => {
        setChatMessages([
          {
            id: 1,
            sender_id: "citizen-101",
            receiver_id: "officer-dm-101",
            role: "citizen",
            message: language === 'aw' 
              ? "हजुर, हमार अर्ज़ी कय का हाल बा? कब तक होई?"
              : "महोदय, मेरी शिकायत की क्या स्थिति है? कब तक निवारण होगा?",
            created_at: new Date(Date.now() - 3600000).toISOString()
          },
          {
            id: 2,
            sender_id: "officer-dm-101",
            receiver_id: "citizen-101",
            role: "officer",
            message: language === 'aw'
              ? "सुनो भैया, तोहार कागज़ कय जांच पूरा होई गवा बा, डीएम साहेब के सिग्नेचर कय इंतज़ार बा।"
              : "नमस्कार, आपका आवेदन ओसीआर एवं नियम जांच पास कर चुका है। वर्तमान में सक्षम अधिकारी के हस्ताक्षर हेतु प्रक्रियाधीन है।",
            created_at: new Date(Date.now() - 1800000).toISOString()
          }
        ]);
      }, 0);
    }
  }

  // Sync and fetch Chat messages whenever activeWorkflowId updates
  useEffect(() => {
    if (activeWorkflow) {
      fetchChatHistory();
    }
  }, [activeWorkflowId, activeWorkflow?.id]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages, isOfficerTyping]);

  const handleSendMessage = async () => {
    if (!chatInput.trim() && !attachedFile) return;
    if (!activeWorkflow) return;

    const currentText = chatInput;
    const currentAttachment = attachedFile;
    setChatInput('');
    setAttachedFile(null);

    const userMsg: ClientChatMessage = {
      id: Math.random(),
      sender_id: "citizen-101",
      receiver_id: "officer-dm-101",
      role: "citizen",
      message: currentText || `Attached evidence document: ${currentAttachment}`,
      attachment_url: currentAttachment || undefined,
      created_at: new Date().toISOString()
    };

    setChatMessages(prev => [...prev, userMsg]);

    try {
      // Save in real sqlite DB via FastAPI router
      await fetch(`${BACKEND_URL}/api/v1/workflows/${activeWorkflow.id}/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: userMsg.message,
          role: "citizen",
          sender_id: "citizen-101",
          attachment_url: currentAttachment
        })
      });
    } catch (e) {
      console.log("Failed to persist message to database.");
    }

    // Trigger officer dynamic conversational response
    setIsOfficerTyping(true);
    setTimeout(async () => {
      setIsOfficerTyping(false);
      let officerReply = "";

      const lowerText = currentText.toLowerCase();
      if (lowerText.includes('pension') || lowerText.includes('पेंशन')) {
        officerReply = language === 'aw'
          ? "अम्मा सुनो, तोहार ओल्ड ऐज पेंशन कय आय प्रमाण पत्र एकदम सही बा। कछू दिन मा सीधे बैंक खाता मा पेंशन आई!"
          : "सादर नमस्कार, आपके वृद्धावस्था पेंशन हेतु आय प्रमाण पत्र का सत्यापन पूर्ण हो गया है। पात्रता सुनिश्चित हो गई है।";
      } else if (lowerText.includes('delay') || lowerText.includes('time') || lowerText.includes('देरी') || lowerText.includes('कब')) {
        officerReply = language === 'aw'
          ? "साहेब सुनो! हज़रतगंज PWD विभाग कय काम ७२ घंटा कय बा। अगर आज रात तक काम ना भवा तौ हम सीधे एक्शन लेब!"
          : "शिकायत का निवारण ७२ घंटे के भीतर सुनिश्चित किया जाएगा। समयावधि पूर्ण होते ही स्वतः अग्रसारित कर दिया जाएगा।";
      } else {
        officerReply = language === 'aw'
          ? "भैया मुस्कुराओ, आप लखनऊ मा हो! हम तोहार अर्ज़ी कय हाल-चाल तुरंतै ठीक करावब, चिंता न करा!"
          : "प्रणाम, आपकी शिकायत दर्ज हो गई है। हमारी विशेष विंग इसकी समीक्षा कर रही है। शीघ्र ही अपडेट किया जाएगा।";
      }

      const officerMsg: ClientChatMessage = {
        id: Math.random(),
        sender_id: "officer-dm-101",
        receiver_id: "citizen-101",
        role: "officer",
        message: officerReply,
        created_at: new Date().toISOString()
      };

      setChatMessages(prev => [...prev, officerMsg]);

      try {
        await fetch(`${BACKEND_URL}/api/v1/workflows/${activeWorkflow.id}/chat`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            message: officerReply,
            role: "officer",
            sender_id: "officer-dm-101"
          })
        });
      } catch (e) {
        console.log("Failed to save officer reply.");
      }
    }, 2000);
  };

  const handlePresetAttachment = (filename: string) => {
    setAttachedFile(filename);
  };

  const filteredWorkflows = workflows.filter(w => 
    w.id.toLowerCase().includes(searchQuery.toLowerCase()) || 
    w.title.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <DashboardLayout>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 max-w-6xl mx-auto h-[calc(100vh-120px)] animate-in fade-in duration-300">
        
        {/* Left Workflow selector queue */}
        <div className="lg:col-span-1 flex flex-col gap-4 h-full overflow-hidden">
          <div className="flex flex-col gap-1 shrink-0">
            <span className="text-[10px] uppercase font-mono font-bold text-cyber-cyan tracking-widest">Tracking Vault</span>
            <h3 className="text-sm font-extrabold text-white">Active Grievance Index</h3>
          </div>

          <div className="relative shrink-0">
            <Search className="absolute left-3 top-3 text-white/40" size={14} />
            <input 
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by application tracking ID..."
              className="w-full bg-white/5 border border-white/10 rounded-lg py-2 pl-9 pr-3 text-xs text-white placeholder-white/35 focus:outline-none focus:border-cyber-cyan/50"
            />
          </div>

          <div className="flex-1 overflow-y-auto flex flex-col gap-3 pr-1">
            {filteredWorkflows.map((w) => {
              const isActive = activeWorkflow?.id === w.id;
              return (
                <div
                  key={w.id}
                  onClick={() => selectWorkflow(w.id)}
                  className={`
                    p-4 rounded-xl border transition cursor-pointer relative overflow-hidden flex flex-col gap-3 group
                    ${isActive 
                      ? 'bg-cyber-cyan/5 border-cyber-cyan/40 shadow-[0_0_15px_rgba(0,240,255,0.05)]' 
                      : 'bg-white/5 border-white/5 hover:border-white/15'
                    }
                  `}
                >
                  <div className="flex justify-between items-start">
                    <span className="text-[9px] font-mono text-cyber-cyan font-bold">{w.id}</span>
                    <span className={`text-[8px] uppercase font-mono font-bold px-2 py-0.5 rounded ${
                      w.status === 'completed' 
                        ? 'bg-cyber-green/10 text-cyber-green border border-cyber-green/20' 
                        : w.status === 'escalated'
                          ? 'bg-cyber-pink/10 text-cyber-pink border border-cyber-pink/20 animate-pulse'
                          : 'bg-cyber-cyan/10 text-cyber-cyan border border-cyber-cyan/20 animate-pulse'
                    }`}>
                      {w.status}
                    </span>
                  </div>

                  <h4 className="text-xs font-bold text-white group-hover:text-cyber-cyan transition line-clamp-1">{w.title}</h4>
                  
                  <div className="flex justify-between items-center text-[10px] text-white/50 font-mono">
                    <span>{w.location.split(',')[0]}</span>
                    <span>{w.progress}% Checked</span>
                  </div>
                  
                  {/* Glowing line for active */}
                  {isActive && (
                    <span className="absolute left-0 top-0 bottom-0 w-[2px] bg-cyber-cyan" />
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Active Timeline and Chat Panel */}
        {activeWorkflow ? (
          <div className="lg:col-span-2 flex flex-col gap-4 h-full overflow-hidden">
            
            {/* Tab navigation headers */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-white/10 pb-3 gap-3 shrink-0 relative z-10 select-none">
              <div className="flex gap-2 bg-[#02030b]/40 p-1.5 rounded-xl border border-white/5 text-[10px] font-extrabold font-mono">
                <button
                  onClick={() => setActiveTab('telemetry')}
                  className={`px-3 py-2 rounded-lg border transition cursor-pointer uppercase ${
                    activeTab === 'telemetry'
                      ? 'bg-cyber-cyan/10 border-cyber-cyan/50 text-cyber-cyan shadow-[0_0_10px_rgba(0,240,255,0.08)]'
                      : 'border-transparent text-white/50 hover:text-white hover:bg-white/5'
                  }`}
                >
                  📡 TELEMETRY & CHAT
                </button>
                <button
                  onClick={() => setActiveTab('diagram')}
                  className={`px-3 py-2 rounded-lg border transition cursor-pointer uppercase ${
                    activeTab === 'diagram'
                      ? 'bg-cyber-purple/10 border-cyber-purple/50 text-cyber-purple shadow-[0_0_10px_rgba(188,19,254,0.08)]'
                      : 'border-transparent text-white/50 hover:text-white hover:bg-white/5'
                  }`}
                >
                  📊 VISUAL WORKFLOW
                </button>
                <button
                  onClick={() => setActiveTab('report')}
                  className={`px-3 py-2 rounded-lg border transition cursor-pointer uppercase ${
                    activeTab === 'report'
                      ? 'bg-cyber-pink/10 border-cyber-pink/50 text-cyber-pink shadow-[0_0_10px_rgba(255,42,133,0.08)]'
                      : 'border-transparent text-white/50 hover:text-white hover:bg-white/5'
                  }`}
                >
                  📝 AI RESOLUTION REPORT
                </button>
              </div>

              {/* Running telemetry label */}
              <div className="flex items-center gap-1.5 text-[9px] font-mono text-white/40 pl-2 pr-1">
                {isRunning ? (
                  <>
                    <span className="h-1.5 w-1.5 rounded-full bg-cyber-pink animate-ping shadow-[0_0_8px_#ff2a85]" />
                    <span className="text-cyber-pink font-bold uppercase tracking-wider animate-pulse">AI BRAIN PROCESSING LIVE</span>
                  </>
                ) : (
                  <>
                    <span className="h-1.5 w-1.5 rounded-full bg-cyber-cyan animate-pulse shadow-[0_0_8px_#00f0ff]" />
                    <span>SOVEREIGN CLOUD OS ACTIVE</span>
                  </>
                )}
              </div>
            </div>

            {/* Active Tab Panel container */}
            <div className="flex-1 overflow-hidden relative">
              {activeTab === 'telemetry' && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 h-full overflow-hidden">
                  
                  {/* Live Timeline logs */}
                  <div className="glass-card p-5 rounded-xl border border-white/5 flex flex-col h-full overflow-hidden relative">
                    <div className="absolute inset-0 cyber-grid opacity-10 pointer-events-none" />
                    
                    <div className="flex justify-between items-center shrink-0 border-b border-white/5 pb-3 relative z-10">
                      <div className="flex flex-col">
                        <span className="text-[9px] font-mono text-cyber-cyan uppercase font-bold tracking-wider">Complaint Milestones</span>
                        <h3 className="text-xs font-extrabold text-white mt-0.5 max-w-[150px] truncate">{activeWorkflow.title}</h3>
                      </div>
                      <button
                        onClick={() => isRunning ? stopSimulation() : startSimulation()}
                        className={`px-3 py-1.5 rounded text-[10px] font-mono font-bold transition cursor-pointer ${
                          isRunning 
                            ? 'bg-cyber-pink text-white shadow-[0_0_10px_#ff2a85] animate-pulse' 
                            : 'bg-cyber-cyan text-navy-950 hover:bg-cyber-cyan/90 shadow-[0_0_10px_rgba(0,240,255,0.2)]'
                        }`}
                      >
                        {isRunning ? 'LOCKED SIM RUNNING' : 'ACTIVATE SIM RUN'}
                      </button>
                    </div>

                    {/* Progress visual bar */}
                    <div className="mt-4 flex flex-col gap-2 shrink-0 relative z-10">
                      <div className="flex justify-between text-[10px] font-mono leading-none">
                        <span className="text-white/40">Ingestion Path Verified</span>
                        <span className="text-cyber-cyan font-bold">{activeWorkflow.progress}%</span>
                      </div>
                      <div className="w-full h-1.5 bg-white/5 rounded-full overflow-hidden border border-white/5">
                        <div className="h-full bg-gradient-to-r from-cyber-cyan via-cyber-purple to-cyber-pink transition-all duration-500 shadow-[0_0_8px_#00f0ff]" style={{ width: `${activeWorkflow.progress}%` }} />
                      </div>
                    </div>

                    {/* Live WebSocket log feed */}
                    <div className="flex-1 overflow-y-auto flex flex-col gap-3 my-4 pr-1 relative z-10">
                      <span className="text-[9px] uppercase font-bold text-white/40 font-mono tracking-wider">AI Multi-Agent Timeline Logs:</span>
                      
                      {logs.length === 0 ? (
                        <div className="py-12 text-center text-xs text-white/35 font-mono">Purging verification pipelines... Ingesting deed credentials.</div>
                      ) : (
                        logs.map((log, i) => (
                          <div key={i} className="flex gap-2.5 items-start text-xs border-b border-white/5 pb-2 hover:bg-white/[0.01] transition p-1 rounded">
                            <div className="mt-0.5">
                              {log.status === 'success' && <CheckCircle2 size={13} className="text-cyber-green shrink-0" />}
                              {log.status === 'error' && <ShieldAlert size={13} className="text-cyber-pink shrink-0 animate-pulse" />}
                              {log.status === 'warning' && <ShieldAlert size={13} className="text-cyber-orange shrink-0 animate-pulse" />}
                              {log.status === 'info' && <Clock size={13} className="text-cyber-cyan shrink-0" />}
                            </div>
                            <div className="flex flex-col gap-0.5 leading-normal">
                              <div className="flex items-center gap-1.5 font-mono text-[9px]">
                                <span className="text-white font-bold">{log.agent}</span>
                                <span className="text-white/30">&bull;</span>
                                <span className="text-white/40">{log.timestamp}</span>
                              </div>
                              <p className="text-white/80 font-sans leading-relaxed">{log.message}</p>
                            </div>
                          </div>
                        ))
                      )}
                    </div>
                  </div>

                  {/* Live Citizen-Officer Chat Panel */}
                  <div className="glass-card rounded-xl border border-white/5 flex flex-col h-full overflow-hidden relative shadow-2xl">
                    <div className="absolute inset-0 cyber-grid opacity-5 pointer-events-none" />
                    
                    {/* Header */}
                    <div className="p-3 bg-navy-950/80 border-b border-white/5 flex items-center justify-between shrink-0 relative z-10">
                      <div className="flex items-center gap-2">
                        <div className="h-2 w-2 rounded-full bg-cyber-green animate-pulse shadow-[0_0_8px_#00ff87]" />
                        <div className="flex flex-col leading-none">
                          <span className="text-[10px] font-extrabold text-white font-mono uppercase tracking-wider">Officer Desk Chat</span>
                          <span className="text-[9px] text-white/50 mt-1">Assigned Division Reviewer</span>
                        </div>
                      </div>
                      <span className="text-[9px] font-mono text-cyber-cyan border border-cyber-cyan/35 px-1.5 py-0.5 rounded uppercase font-bold tracking-wider">DM Secured</span>
                    </div>

                    {/* Chat Bubble Body */}
                    <div className="flex-1 overflow-y-auto p-3 flex flex-col gap-3 bg-[#02030b]/20 relative z-10">
                      {chatMessages.map((m) => {
                        const isOfficer = m.role === 'officer';
                        return (
                          <div 
                            key={m.id}
                            className={`flex gap-2 max-w-[85%] animate-in fade-in slide-in-from-bottom-1 duration-200 ${isOfficer ? 'self-start' : 'self-end flex-row-reverse'}`}
                          >
                            <div className={`
                              h-7 w-7 rounded-full flex items-center justify-center shrink-0 text-[10px] font-mono font-bold
                              ${isOfficer ? 'bg-cyber-cyan/15 border border-cyber-cyan/30 text-cyber-cyan' : 'bg-cyber-purple/15 border border-cyber-purple/30 text-cyber-purple'}
                            `}>
                              {isOfficer ? 'OFF' : 'CIT'}
                            </div>
                            
                            <div className="flex flex-col gap-1">
                              <div className={`
                                p-2.5 rounded-lg border text-[11px] leading-relaxed
                                ${isOfficer 
                                  ? 'bg-navy-950/95 border-white/5 text-white shadow-md' 
                                  : 'bg-gradient-to-r from-cyber-cyan/10 to-cyber-blue/5 border-cyber-cyan/20 text-white'
                                }
                              `}>
                                {m.message}
                                {m.attachment_url && (
                                  <div className="mt-2 p-1.5 rounded bg-white/5 border border-white/10 flex items-center gap-1.5 text-[9px] font-mono">
                                    <Paperclip size={10} className="text-cyber-cyan" />
                                    <span>{m.attachment_url}</span>
                                  </div>
                                )}
                              </div>
                              <span className="text-[8px] text-white/30 self-end font-mono leading-none mt-0.5">{new Date(m.created_at).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</span>
                            </div>
                          </div>
                        );
                      })}

                      {isOfficerTyping && (
                        <div className="flex gap-2 self-start items-center">
                          <div className="h-7 w-7 rounded-full bg-cyber-cyan/15 border border-cyber-cyan/30 text-cyber-cyan flex items-center justify-center shrink-0 animate-pulse text-[10px] font-mono">
                            OFF
                          </div>
                          <div className="p-2 rounded-lg bg-navy-950/80 border border-white/5 flex gap-1 items-center">
                            <span className="h-1.5 w-1.5 rounded-full bg-cyber-cyan animate-bounce" style={{ animationDelay: '0s' }} />
                            <span className="h-1.5 w-1.5 rounded-full bg-cyber-cyan animate-bounce" style={{ animationDelay: '0.15s' }} />
                            <span className="h-1.5 w-1.5 rounded-full bg-cyber-cyan animate-bounce" style={{ animationDelay: '0.3s' }} />
                          </div>
                        </div>
                      )}
                      <div ref={chatEndRef} />
                    </div>

                    {/* Input Area */}
                    <div className="p-2 bg-navy-950 border-t border-white/5 flex flex-col gap-2 shrink-0 z-10 relative">
                      {attachedFile && (
                        <div className="p-1 rounded bg-cyber-cyan/10 border border-cyber-cyan/30 flex items-center justify-between text-[9px] font-mono">
                          <span className="flex items-center gap-1"><Paperclip size={10} /> Attached: {attachedFile}</span>
                          <button onClick={() => setAttachedFile(null)} className="text-cyber-pink font-bold">&times;</button>
                        </div>
                      )}

                      <div className="flex gap-2 items-center">
                        <button 
                          onClick={() => handlePresetAttachment(`${activeWorkflow.type}_evidence_record.pdf`)}
                          className="p-2 rounded bg-white/5 border border-white/10 hover:border-cyber-cyan/40 text-white/50 hover:text-white transition cursor-pointer"
                          title="Attach Evidence"
                        >
                          <Paperclip size={12} />
                        </button>
                        
                        <input 
                          type="text"
                          value={chatInput}
                          onChange={(e) => setChatInput(e.target.value)}
                          onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                          placeholder="Ask officer about status or send response details..."
                          className="flex-1 bg-white/5 border border-white/10 rounded-lg py-2 px-3 text-xs text-white placeholder-white/30 focus:outline-none focus:border-cyber-cyan/50"
                        />
                        
                        <button 
                          onClick={handleSendMessage}
                          className="p-2 rounded bg-cyber-cyan text-navy-950 font-bold hover:bg-cyber-cyan/90 hover:shadow-[0_0_10px_rgba(0,240,255,0.4)] transition cursor-pointer"
                        >
                          <Send size={12} />
                        </button>
                      </div>
                    </div>
                  </div>

                </div>
              )}

              {activeTab === 'diagram' && renderVisualWorkflowDiagram()}

              {activeTab === 'report' && renderAiResolutionReport()}
            </div>

          </div>
        ) : (
          <div className="lg:col-span-2 glass-card py-24 text-center text-white/30 text-xs font-mono">
            Select a complaint or application to start live telemetry tracking
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
